platform :ios, '13.0'

target 'POSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'

  # Pods for POSApp

  target 'POSAppTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

end
